rules:
  - id: detect-gcp-api-key
    pattern-regex: 'AIza[0-9A-Za-z\-_]{35}'
    message: "GCP API key detected"
    languages: [generic]
    severity: "ERROR"

  - id: detect-passwords
    pattern-regex: '(?:password|pwd|pass)\s*[=:]\s*["\'][^"\']{12,}["\']'
    message: "Potential hardcoded password detected"
    languages: [generic]
    severity: "WARNING"
    metadata:
      # Only flag actual hardcoded passwords (12+ chars), not variable names
      # Excludes common patterns like environment variables and function params
      false-positives:
        - "Environment variable assignments"
        - "Function parameter definitions"
        - "Variable declarations"
        - "Configuration keys"

  - id: detect-private-key
    pattern-regex: '-----BEGIN [A-Z ]*PRIVATE KEY-----'
    message: "Private key detected"
    languages: [generic]
    severity: "ERROR"