
#composite tasks
[tasks.upgrade]
dependencies = ["upgrade-deps", "update"]

# format
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

# cleaning
[tasks.clean-state]
script = """
rm hello-*.state
"""

[tasks.clean]
command = "cargo"
args = ["clean"]

# building
[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.build-clean]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

# testing
[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

# linting
[tasks.lint]
command = "cargo"
args = ["clippy"]
dependencies = ["build"]

[tasks.lint-fix]
command = "cargo"
args = ["clippy", "--fix"]
dependencies = ["build"]

[tasks.bloat]
command = "cargo"
args = ["bloat", "${@}"]
dependencies = ["build"]

[tasks.leptos]
command = "cargo"
args = ["leptos", "${@}"]
dependencies = ["build"]

[tasks.machete]
command = "cargo"
args = ["machete"]
dependencies = ["build"]

[tasks.outdated]
command = "cargo"
args = ["outdated"]
dependencies = ["build"]

[tasks.security]
command = "cargo"
args = ["audit"]
dependencies = ["build"]

[tasks.sort]
command = "cargo"
args = ["sort"]
dependencies = ["build"]

[tasks.spellcheck]
command = "cargo"
args = ["spellcheck", "fix"]
dependencies = ["build"]

[tasks.udeps]
toolchain = "nightly"
command = "cargo"
args = ["udeps"]
dependencies = ["build"]

[tasks.valgrind]
command = "cargo"
args = ["valgrind"]
dependencies = ["build"]

[tasks.cargo-check]
dependencies = [
	"security",
	"bloat",
	"udeps",
]

# dependency management
[tasks.upgrade-deps]
command = "cargo"
args = ["upgrade"]

[tasks.update]
command = "cargo"
args = ["update"]

# rebuild
[tasks.rebuild]
dependencies = [
	"format",
	"build",
	"test"
]

[tasks.rebuild-clean]
dependencies = [
	"format",
	"build-clean",
	"test"
]
