# DigitalOcean App Platform configuration for alexthola.com
name: blog
region: nyc

# Main application service
services:
  - name: blog-web
    source_dir: .
    github:
      repo: athola/blog
      branch: master
      deploy_on_push: true

    # Use custom Dockerfile for multi-stage build
    dockerfile_path: Dockerfile

    # Explicit run command ensures Dockerfile binary is used.
    run_command: /app/blog

    # Runtime configuration
    instance_count: 1
    instance_size_slug: basic-xxs

    # Port configuration
    http_port: 8080

    # Environment variables for SurrealDB connection
    envs:
      - key: PORT
        value: "8080"
      - key: RUST_LOG
        value: info
      - key: LEPTOS_SITE_ADDR
        value: 0.0.0.0:8080
      - key: LEPTOS_SITE_ROOT
        value: site
      - key: LEPTOS_HASH_FILES
        value: "true"
      - key: SURREAL_ADDRESS
        value: ${SURREAL_ADDRESS}
        type: SECRET
      - key: SURREAL_NS
        value: ${SURREAL_NS}
        type: SECRET
      - key: SURREAL_DB
        value: ${SURREAL_DB}
        type: SECRET
      - key: SURREAL_ROOT_USER
        value: ${SURREAL_ROOT_USER}
        type: SECRET
      - key: SURREAL_ROOT_PASS
        value: ${SURREAL_ROOT_PASS}
        type: SECRET
      # SMTP configuration (optional - for contact form)
      - key: SMTP_HOST
        value: ${SMTP_HOST}
        type: SECRET
      - key: SMTP_USER
        value: ${SMTP_USER}
        type: SECRET
      - key: SMTP_PASSWORD
        value: ${SMTP_PASSWORD}
        type: SECRET

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      failure_threshold: 3
      success_threshold: 1

# Domain configuration
domains:
  - domain: alexthola.com
    type: PRIMARY
    wildcard: false
  - domain: www.alexthola.com
    type: ALIAS
    wildcard: false

# Static assets (none needed - handled by app)
static_sites: []

# Worker services (none needed)
workers: []

# Jobs (migrations handled by GitHub Actions)
jobs: []

# Monitoring alerts
alerts:
  - rule: CPU_UTILIZATION
    disabled: false
    operator: GREATER_THAN
    value: 80
    window: FIVE_MINUTES
  - rule: MEM_UTILIZATION
    disabled: false
    operator: GREATER_THAN
    value: 80
    window: FIVE_MINUTES
  - rule: RESTART_COUNT
    disabled: false
    operator: GREATER_THAN
    value: 3
    window: FIVE_MINUTES

# Ingress rules
ingress:
  rules:
    - match:
        path:
          prefix: "/"
      component:
        name: blog-web
