//! `app` crate provides the core Leptos application logic, including the main shell,
//! root component, routing, and shared UI components.
//!
//! This crate is responsible for:
//! - Setting up the HTML shell and meta context.
//! - Defining the main application component and its routes.
//! - Integrating various sub-components like headers, footers, and page-specific views.
//! - Handling global error fallbacks.

use crate::components::{error_template, header, icons};
use chrono::{Datelike as _, Utc};
#[cfg(feature = "ssr")]
use leptos::html::{body, head, html, meta};
use leptos::{
    html::{a, div, footer, p},
    prelude::*,
};
use leptos_meta::provide_meta_context;
#[cfg(feature = "ssr")]
use leptos_meta::{MetaTags, Stylesheet, StylesheetProps, Title, TitleProps};
use leptos_router::{
    ParamSegment, SsrMode, StaticSegment,
    components::{FlatRoutes, Route, Router},
};
#[cfg(feature = "ssr")]
use std::sync::{Arc, OnceLock};

mod activity;
pub mod api; // API endpoints and types
mod components; // Reusable UI components
mod contact; // Contact page logic and components
mod home; // Homepage logic and components
mod post; // Post display logic and components
mod references; // References page logic and components
pub mod types; // Shared type definitions

#[cfg(feature = "ssr")]
/// Builds the CSS href from hash file content, appending the content hash when present.
///
/// Parses cargo-leptos hash file format (`css: <hash>`) and constructs a URL like
/// `/pkg/{output_name}.{hash}.css`. Returns the unhashed URL if hashing is disabled
/// or the CSS hash is not found.
fn build_css_href(output_name: &str, hash_files: bool, hash_content: Option<&str>) -> String {
    if hash_files {
        if let Some(css_hash) = hash_content
            .into_iter()
            .flat_map(|content| content.lines())
            .filter_map(|line| line.split_once(':'))
            .find(|(key, _)| key.trim() == "css")
            .map(|(_, hash)| hash.trim().to_string())
        {
            return format!("/pkg/{output_name}.{css_hash}.css");
        }
        #[cfg(feature = "ssr")]
        if hash_content.is_some() {
            tracing::warn!(
                "Hash file was read but contains no 'css:' entry — falling back to unhashed CSS"
            );
        }
    }
    format!("/pkg/{output_name}.css")
}

#[cfg(feature = "ssr")]
/// Resolves the CSS filename, appending the content hash when `hash_files` is enabled.
///
/// Mirrors the approach used by Leptos' `HydrationScripts` for JS/WASM, but for CSS
/// which Leptos does not handle automatically. Reads the `css:` key from the hash file
/// generated by cargo-leptos. Result is cached via `OnceLock`.
fn resolve_css_href(options: &LeptosOptions) -> String {
    static CSS_HREF: OnceLock<String> = OnceLock::new();
    CSS_HREF
        .get_or_init(|| {
            let hash_content = if options.hash_files {
                let exe_dir = match std::env::current_exe() {
                    Ok(path) => path.parent().map(|p| p.to_path_buf()).unwrap_or_default(),
                    Err(e) => {
                        tracing::warn!(
                            "Could not determine executable path: {e}. \
                             Hash file lookup will use current working directory."
                        );
                        std::path::PathBuf::new()
                    }
                };
                let hash_path = exe_dir.join(options.hash_file.as_ref());
                match std::fs::read_to_string(&hash_path) {
                    Ok(content) => Some(content),
                    Err(e) => {
                        tracing::error!(
                            "CSS hash file could not be read at {}: {e}. \
                             Falling back to unhashed CSS URL.",
                            hash_path.display()
                        );
                        None
                    }
                }
            } else {
                None
            };
            build_css_href(
                &options.output_name,
                options.hash_files,
                hash_content.as_deref(),
            )
        })
        .clone()
}

#[cfg(feature = "ssr")]
/// Renders the HTML shell for the application, including `<head>` and `<body>` content.
///
/// This function sets up the basic HTML structure, integrates meta tags, stylesheets,
/// and hydration scripts, and then renders the main application component within the `<body>`.
pub fn shell(options: Arc<LeptosOptions>) -> impl IntoView {
    let css_href = resolve_css_href(&options);

    // Unwraps the Arc to get LeptosOptions. If the Arc has multiple strong references,
    // it clones the options; otherwise, it takes ownership.
    let options = Arc::try_unwrap(options).unwrap_or_else(|shared| shared.as_ref().clone());

    // Provides context for managing stylesheets, titles, meta tags, etc., throughout the app.
    provide_meta_context();

    let html_comp = html().lang("en").child((
        head().child((
            meta().charset("utf-8"),
            meta()
                .name("viewport")
                .content("width=device-width, initial-scale=1"),
            // AutoReload(AutoReloadProps::builder().options(options.clone()).build()),
            HydrationScripts(HydrationScriptsProps::builder().options(options).build()),
            MetaTags(),
            Stylesheet(
                StylesheetProps::builder()
                    .id("leptos")
                    .href(css_href)
                    .build(),
            ),
            Stylesheet(
                StylesheetProps::builder()
                    .id("katex")
                    .href("/public/katex.min.css")
                    .build(),
            ),
            Title(
                TitleProps::builder()
                    .text("Alex Thola's Blog \u{2013} Tech Insights & Consulting")
                    .build(),
            ),
        )),
        body().class("bg-[#1e1e1e]").child(self::component),
    ));

    view! {
        <!DOCTYPE html>
        {html_comp}
    }
}

/// The root component of the application, responsible for defining the main layout and routing.
///
/// This component sets up the router, global layout (header, main content area, footer),
/// and defines the application's routes. It also includes a fallback for 404 (Not Found) errors.
#[must_use]
pub fn component() -> impl IntoView {
    provide_meta_context();

    view! {
        <Router>
            <div class="overflow-auto text-white font-poppins">
                {move || header::component}
                <main class="container flex flex-col gap-8 px-4 pt-10 pb-14 mx-auto mt-16 max-w-4xl md:px-0">
                    <FlatRoutes fallback=|| {
                        // Handle 404 (Not Found) errors by rendering a specific error template.
                        let mut outside_errors = Errors::default();
                        outside_errors.insert_with_default_key(error_template::AppError::NotFound);
                        error_template::component(Some(outside_errors), None)
                    }>
                        <Route path=StaticSegment("") view=home::component ssr=SsrMode::InOrder/>
                        <Route path=StaticSegment("references") view=references::component/>
                        <Route path=StaticSegment("contact") view=contact::component/>
                        <Route path=(StaticSegment("post"), ParamSegment("slug")) view=post::component ssr=SsrMode::Async/>
                        <Route path=StaticSegment("activity") view=activity::component/>
                    </FlatRoutes>
                </main>
                {footer_component()}
            </div>
        </Router>
    }
}

/// Renders the application's footer component.
///
/// This includes copyright information, a link to the author's GitHub, and dynamically
/// displays the current year. It also conditionally shows icons on smaller screens.
fn footer_component() -> impl IntoView {
    footer()
        .class("fixed right-0 bottom-0 left-0 z-10 py-2 text-center md:py-4 bg-[#1e1e1e]/80 backdrop-blur-md")
        .child(
            div().class("flex flex-col gap-1 justify-center items-center").child((
                p().class("text-gray-400").child((
                    "Powered by",
                    a()
                        .href("https://github.com/athola")
                        .class("hover:underline text-[#ffef5c]")
                        .child(" athola"),
                    format!(" \u{a9} {}", Utc::now().year()),
                )),
                div().class("block md:hidden").child(icons::component),
            )),
        )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    /// Test the shell function to ensure it creates a view without panicking.
    fn test_shell_creation() {
        // Create default LeptosOptions for testing.
        let options = LeptosOptions::builder().output_name("blog").build();
        let shell_view = shell(Arc::new(options));
        // Consume the view to confirm successful creation and prevent unused variable warnings.
        drop(shell_view);
    }

    #[test]
    /// Verify that core component functions (`shell`, `component`) exist with correct signatures.
    fn test_component_function_signatures() {
        // Ensure function signatures compile and are callable.
        let _shell_fn: fn(Arc<LeptosOptions>) -> _ = shell;
        let _component_fn: fn() -> _ = component;

        // Test that LeptosOptions can be created and has expected default values.
        let options = LeptosOptions::builder().output_name("blog").build();
        assert_eq!(options.site_addr.port(), 3000); // Check default port.
        assert_eq!(options.site_addr.ip().to_string(), "127.0.0.1"); // Check default IP.
    }

    #[test]
    fn build_css_href_returns_unhashed_when_disabled() {
        let href = build_css_href("blog", false, None);
        assert_eq!(href, "/pkg/blog.css");
    }

    #[test]
    fn build_css_href_returns_unhashed_when_no_hash_content() {
        let href = build_css_href("blog", true, None);
        assert_eq!(href, "/pkg/blog.css");
    }

    #[test]
    fn build_css_href_returns_hashed_with_valid_content() {
        let content = "js: abc123\nwasm: def456\ncss: 16KG87DE62CeLFrc3kkwgw\n";
        let href = build_css_href("blog", true, Some(content));
        assert_eq!(href, "/pkg/blog.16KG87DE62CeLFrc3kkwgw.css");
    }

    #[test]
    fn build_css_href_returns_unhashed_when_css_key_missing() {
        let content = "js: abc123\nwasm: def456\n";
        let href = build_css_href("blog", true, Some(content));
        assert_eq!(href, "/pkg/blog.css");
    }

    #[test]
    fn build_css_href_handles_whitespace_in_hash() {
        let content = "css:   spaced_hash  \n";
        let href = build_css_href("blog", true, Some(content));
        assert_eq!(href, "/pkg/blog.spaced_hash.css");
    }

    #[test]
    fn build_css_href_uses_output_name() {
        let content = "css: myhash\n";
        let href = build_css_href("my-app", true, Some(content));
        assert_eq!(href, "/pkg/my-app.myhash.css");
    }

    #[test]
    fn build_css_href_returns_unhashed_when_content_is_empty_string() {
        let href = build_css_href("blog", true, Some(""));
        assert_eq!(href, "/pkg/blog.css");
    }

    #[test]
    fn build_css_href_uses_first_css_key_when_duplicated() {
        let content = "css: first_hash\ncss: second_hash\n";
        let href = build_css_href("blog", true, Some(content));
        assert_eq!(href, "/pkg/blog.first_hash.css");
    }

    #[test]
    fn build_css_href_ignores_content_when_hashing_disabled() {
        let content = "css: some_hash\n";
        let href = build_css_href("blog", false, Some(content));
        assert_eq!(href, "/pkg/blog.css");
    }

    #[cfg(feature = "ssr")]
    #[test]
    /// Confirm that server function signatures remain consistent after retry implementation.
    fn test_server_functions_integration() {
        use crate::api::*;

        // Verify server function signatures are unchanged by retry logic.
        let _posts_fn: fn(Vec<String>) -> _ = select_posts;
        let _tags_fn: fn() -> _ = select_tags;
        let _post_fn: fn(String) -> _ = select_post;
        let _views_fn: fn(String) -> _ = increment_views;
        let _contact_fn: fn(ContactRequest) -> _ = contact;
        let _refs_fn: fn() -> _ = select_references;

        // Ensure a ContactRequest can be created with expected default field values.
        let request = ContactRequest::default();
        assert_eq!(request.name, "");
        assert_eq!(request.email, "");
        assert_eq!(request.subject, "");
        assert_eq!(request.message, "");
    }
}
