[profile.default]
# Force single-threaded execution for all tests to avoid resource conflicts
test-threads = 1

# Additional settings to ensure proper test isolation
fail-fast = false
retries = 0

# Override for server integration tests to ensure they get exclusive access
[[profile.default.overrides]]
filter = 'test(/server_integration_tests/)'
threads-required = 1