name: Database Migrations

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - "migrations/**"
      - "schemas/**"
      - "events/**"
      - "**/*.surql"
      - "db.sh"
  push:
    branches: [ "master" ]
    paths:
      - "migrations/**"
      - "schemas/**"
      - "events/**"
      - "**/*.surql"
      - "db.sh"

permissions:
  contents: read

jobs:
  # Syntax validation for all migration changes - no database access required
  migration-syntax-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Syntax checks should be quick
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        sparse-checkout: |
          migrations/
          schemas/
          events/
          **/*.surql
          db.sh
        sparse-checkout-cone-mode: false
    
    - name: Cache SurrealDB CLI
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/.surrealdb
        key: surrealdb-cli-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          surrealdb-cli-${{ runner.os }}-
    
    - name: Install SurrealDB CLI
      timeout-minutes: 5  # Downloads should be quick
      run: |
        set -euo pipefail  # Exit on error, undefined vars, and pipe failures
        
        if [ ! -f "$HOME/.surrealdb/surreal" ]; then
          # Use latest stable version
          SURREAL_VERSION="v2.3.7"
          SURREAL_URL="https://github.com/surrealdb/surrealdb/releases/download/${SURREAL_VERSION}/surreal-${SURREAL_VERSION}.linux-amd64.tgz"
          
          mkdir -p "$HOME/.surrealdb"
          cd "$HOME/.surrealdb"
          timeout 120 curl -sSL "$SURREAL_URL" -o surreal.tgz  # 2 minute download limit
          tar -xzf surreal.tgz
          chmod +x surreal
          rm surreal.tgz
        fi
        echo "$HOME/.surrealdb" >> $GITHUB_PATH
    
    - name: Validate migration syntax
      timeout-minutes: 5  # Syntax validation should be fast
      run: |
        set -euo pipefail  # Exit on error, undefined vars, and pipe failures
        
        echo "::notice::Validating migration syntax (no database access required)"
        if surreal validate "migrations/*.surql"; then
          echo "✅ All migration files have valid syntax"
        else
          echo "::error::Migration syntax validation failed"
          exit 1
        fi

  # Integration tests for migrations
  migration-integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Integration tests can take longer
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: dtolnay/rust-toolchain@55d80eb3c5a4228eec5390a083c092095115c6f1 # nightly
    
    - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      with:
        shared-key: "migration-tests"
        cache-targets: "true"
        cache-on-failure: "true"
        save-if: ${{ github.ref == 'refs/heads/main' }}
        workspaces: |
          .
        cache-all-crates: "true"
    
    - name: Cache SurrealDB CLI
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/.surrealdb
        key: surrealdb-cli-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          surrealdb-cli-${{ runner.os }}-
    
    - name: Install SurrealDB CLI
      timeout-minutes: 5  # Downloads should be quick
      run: |
        set -euo pipefail  # Exit on error, undefined vars, and pipe failures
        
        if [ ! -f "$HOME/.surrealdb/surreal" ]; then
          # Use latest stable version
          SURREAL_VERSION="v2.3.7"
          SURREAL_URL="https://github.com/surrealdb/surrealdb/releases/download/${SURREAL_VERSION}/surreal-${SURREAL_VERSION}.linux-amd64.tgz"
          
          mkdir -p "$HOME/.surrealdb"
          cd "$HOME/.surrealdb"
          timeout 120 curl -sSL "$SURREAL_URL" -o surreal.tgz  # 2 minute download limit
          tar -xzf surreal.tgz
          chmod +x surreal
          rm surreal.tgz
        fi
        echo "$HOME/.surrealdb" >> $GITHUB_PATH
    
    - name: Install test tools
      run: |
        set -euo pipefail  # Exit on error, undefined vars, and pipe failures
        
        cargo install --locked cargo-nextest cargo-llvm-cov
    
    - name: Run migration integration tests
      timeout-minutes: 15
      run: |
        # Start database for tests
        ./db.sh &
        DB_PID=$!
        
        # Wait for database to be ready
        echo "Waiting for database to be ready..."
        i=1
        while [ $i -le 30 ]; do
            if curl -s http://127.0.0.1:8000/health >/dev/null 2>&1; then
                echo "Database is ready"
                break
            fi
            if [ $i -eq 30 ]; then
                echo "Database did not become ready within 30 seconds"
                kill $DB_PID 2>/dev/null || true
                exit 1
            fi
            echo "Waiting for database... ($i/30)"
            sleep 1
            i=$((i + 1))
        done
        
        # Initialize database
        make init-db
        
        # Run migration tests
        cargo nextest run --workspace -- migration
        
        # Cleanup database process
        kill $DB_PID 2>/dev/null || true
        wait $DB_PID 2>/dev/null || true
    
    - name: Upload migration test results
      if: always()
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: migration-test-results
        path: |
          test-results/
        retention-days: 7

  # Full migration check for trusted PRs from same repository
  migration-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Database connectivity + migration validation
    # Temporarily disabled until DigitalOcean database is properly configured
    # Only run for PRs from the same repository (trusted context)
    if: false  # Disabled until DigitalOcean setup is complete
    environment: migration-validation
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        sparse-checkout: |
          migrations/
          schemas/
          events/
          **/*.surql
          db.sh
        sparse-checkout-cone-mode: false
    
    - name: Test SurrealDB connectivity
      id: connectivity-check
      timeout-minutes: 8  # 5 attempts with backoff should complete within 8 minutes
      run: |
        set -euo pipefail  # Exit on error, undefined vars, and pipe failures
        
        echo "Testing SurrealDB connectivity with retry logic..."
        
        # Retry function with exponential backoff
        retry_with_backoff() {
          local max_attempts=5
          local timeout=10
          local attempt=1
          local exitCode=0
          local max_wait=60  # Cap maximum wait time at 60 seconds
          
          while (( attempt <= max_attempts )); do
            echo "Attempt $attempt of $max_attempts (timeout: ${timeout}s)"
            
            if timeout ${timeout}s curl -f "${{ secrets.SURREAL_ADDRESS }}/status"; then
              echo "✅ SurrealDB is reachable"
              echo "connectivity=success" >> $GITHUB_OUTPUT
              return 0
            fi
            
            exitCode=$?
            echo "Attempt $attempt failed with exit code $exitCode"
            
            if (( attempt < max_attempts )); then
              local wait_time=$((timeout * attempt))
              # Cap wait time to prevent excessive delays
              wait_time=$((wait_time > max_wait ? max_wait : wait_time))
              echo "Waiting ${wait_time} seconds before retry..."
              sleep $wait_time
              timeout=$((timeout > 30 ? timeout : timeout * 2))  # Cap individual timeout
            fi
            
            ((attempt++))
          done
          
          echo "❌ SurrealDB is unreachable at ${{ secrets.SURREAL_ADDRESS }} after $max_attempts attempts"
          echo "connectivity=failed" >> $GITHUB_OUTPUT
          return 1
        }
        
        retry_with_backoff
      continue-on-error: true
    
    - name: Check migrations
      if: steps.connectivity-check.outputs.connectivity == 'success'
      uses: Odonno/surrealdb-migrations-action@c805f03e042cc857c3085a4ff31b22912d7f7da9 # v0.2.0
      with:
        address: ${{ secrets.SURREAL_ADDRESS }}
        ns: ${{ secrets.SURREAL_NS }}
        db: ${{ secrets.SURREAL_DB }}
        username: ${{ secrets.SURREAL_USERNAME }}
        password: ${{ secrets.SURREAL_PASSWORD }}
        version: v2.0.0-preview.1
        skip-untracked-files: true
        dry-run: true
    
    - name: Handle connectivity failure
      if: steps.connectivity-check.outputs.connectivity == 'failed'
      run: |
        set -euo pipefail  # Exit on error, undefined vars, and pipe failures
        
        echo "::error title=SurrealDB Unreachable::Cannot connect to SurrealDB at ${{ secrets.SURREAL_ADDRESS }}. Please check:"
        echo "::error::1. Database server is running"
        echo "::error::2. Network connectivity is available"
        echo "::error::3. SURREAL_ADDRESS secret is correctly configured"
        echo "::error::4. Firewall rules allow connections"
        exit 1