name: Database Migrations

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "migrations/**"
      - "schemas/**"
      - "events/**"
      - "**/*.surql"
      - "db.sh"

jobs:
  migration-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check migrations
      uses: Odonno/surrealdb-migrations-action@v0.2.0
      with:
        address: ${{ secrets.SURREAL_ADDRESS }}
        ns: ${{ secrets.SURREAL_NS }}
        db: ${{ secrets.SURREAL_DB }}
        username: ${{ secrets.SURREAL_USERNAME }}
        password: ${{ secrets.SURREAL_PASSWORD }}
        version: v2.0.0-preview.1
        skip-untracked-files: true
        dry-run: true